apiVersion: apps/v1
kind: Deployment
metadata:
  name: jyothika-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jyothika-todo
  template:
    metadata:
      labels:
        app: jyothika-todo
    spec:
      containers:
        - name: todo-container
          image: docker-todo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80